const data = [
    [`Anaerobic pneumonia- name the bacteria?`, `Peptostreptococcus`],
    [
      `Heinz body seen where?`,
      `a. Intracellular inclusions seen in thalassemia, G6PD deficiency, and
    postsplenectomy. 
    b. G6PD deficiency 
    i. Causes of oxidative stress in G6PD deficiency include
    infection, metabolic acidosis, fava beans, antimalarials,
    dapsone, sulfonamides, and nitrofurantoin.
    ii. An X-linked recessive disease that ↑ RBC sensitivity to
    oxidative stress.`
    ],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`],
    [`xxx`, `xxx`]
  ];

const questionNode = document.getElementById('questions');

const [question, answer] = data[0];
console.log(questionNode);
let p = document.createElement('p');
p.innerHTML = question;
questionNode.appendChild(p)






